inputs:
  docker_cache_enabled:
    required: true
    default: false

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "PROTECTED_RUN=false" >> $GITHUB_ENV
        echo "IMG_REGISTRY=ghcr.io/slyngdk/" >> $GITHUB_ENV
        echo "IMG_NAME_CONTROLLER=nodedrain-controller" >> $GITHUB_ENV
        echo "IMG_NAME_EXAM_PLUGIN=nodedrain-example-plugin" >> $GITHUB_ENV

    - shell: bash
      if: (github.ref == 'refs/heads/main' || (github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v'))) && !env.ACT
      run: |
        echo "PROTECTED_RUN=true" >> $GITHUB_ENV

    - shell: bash
      if: inputs.docker_cache_enabled == 'true'
      run: |
        echo "DOCKER_BUILD_OPTIONS_CONTROLLER=--cache-to type=gha,mode=max,scope=controller-${{ github.ref_name }} --cache-from type=gha,scope=controller-${{ github.ref_name }} --cache-from type=gha,scope=controller-main" >> $GITHUB_ENV
        echo "DOCKER_BUILD_OPTIONS_EXAM_PLUGIN=--cache-to type=gha,mode=max,scope=example-plugin-${{ github.ref_name }} --cache-from type=gha,scope=example-plugin-${{ github.ref_name }} --cache-from type=gha,scope=example-plugin-main" >> $GITHUB_ENV

    - uses: docker/setup-buildx-action@v3
      if: inputs.docker_cache_enabled == 'true'
      id: setup-buildx

    - name: Go Build Cache for Docker
      uses: actions/cache@v4
      if: inputs.docker_cache_enabled == 'true'
      id: cache
      with:
        path: go-build-cache
        key: ${{ runner.os }}-go-build-cache-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-build-cache-

    - name: Restore Docker cache mounts
      uses: reproducible-containers/buildkit-cache-dance@v3.3.0
      if: inputs.docker_cache_enabled == 'true'
      with:
        builder: ${{ steps.setup-buildx.outputs.name }}
        cache-dir: go-build-cache
        dockerfile: Dockerfile

    - name: Expose GitHub Runtime
      uses: crazy-max/ghaction-github-runtime@v3
      if: inputs.docker_cache_enabled == 'true' && !env.ACT
