version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - forbidigo
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - iface
    - ineffassign
    - lll
    - loggercheck
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - wastedassign
  settings:
    govet:
      enable-all: true
      disable:
        - shadow
        - fieldalignment
    loggercheck:
      klog: true
      logr: true
      slog: true
      zap: true
      no-printf-like: true
      require-string-key: true
    revive:
      rules:
        - name: comment-spacings
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        path: api/*
      - linters:
          - dupl
          - lll
        path: internal/*
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
