---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-drain-k8s-slyng-dk-v1-node
  failurePolicy: Fail
  name: mnode-v1.kb.io
  rules:
  - apiGroups:
    - drain.k8s.slyng.dk
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-drain-k8s-slyng-dk-v1-node
  failurePolicy: Fail
  name: vnode-v1.kb.io
  rules:
  - apiGroups:
    - drain.k8s.slyng.dk
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
  sideEffects: None
