---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- resources:
  - node
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - drain.k8s.slyng.dk
  resources:
  - nodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - drain.k8s.slyng.dk
  resources:
  - nodes/finalizers
  verbs:
  - update
- apiGroups:
  - drain.k8s.slyng.dk
  resources:
  - nodes/status
  verbs:
  - get
  - patch
  - update
