// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: api/plugins/proto/v1/drain_plugin.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_api_plugins_proto_v1_drain_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_proto_v1_drain_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_api_plugins_proto_v1_drain_plugin_proto_rawDescGZIP(), []int{0}
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_api_plugins_proto_v1_drain_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_proto_v1_drain_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_api_plugins_proto_v1_drain_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *InitResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type IsSupportedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Supported     bool                   `protobuf:"varint,1,opt,name=supported,proto3" json:"supported,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsSupportedResponse) Reset() {
	*x = IsSupportedResponse{}
	mi := &file_api_plugins_proto_v1_drain_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsSupportedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsSupportedResponse) ProtoMessage() {}

func (x *IsSupportedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_proto_v1_drain_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsSupportedResponse.ProtoReflect.Descriptor instead.
func (*IsSupportedResponse) Descriptor() ([]byte, []int) {
	return file_api_plugins_proto_v1_drain_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *IsSupportedResponse) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}

type IsHealthyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsHealthyRequest) Reset() {
	*x = IsHealthyRequest{}
	mi := &file_api_plugins_proto_v1_drain_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsHealthyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsHealthyRequest) ProtoMessage() {}

func (x *IsHealthyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_proto_v1_drain_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsHealthyRequest.ProtoReflect.Descriptor instead.
func (*IsHealthyRequest) Descriptor() ([]byte, []int) {
	return file_api_plugins_proto_v1_drain_plugin_proto_rawDescGZIP(), []int{3}
}

type IsHealthyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsHealthyResponse) Reset() {
	*x = IsHealthyResponse{}
	mi := &file_api_plugins_proto_v1_drain_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsHealthyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsHealthyResponse) ProtoMessage() {}

func (x *IsHealthyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_proto_v1_drain_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsHealthyResponse.ProtoReflect.Descriptor instead.
func (*IsHealthyResponse) Descriptor() ([]byte, []int) {
	return file_api_plugins_proto_v1_drain_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *IsHealthyResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

type IsSupportedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsSupportedRequest) Reset() {
	*x = IsSupportedRequest{}
	mi := &file_api_plugins_proto_v1_drain_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsSupportedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsSupportedRequest) ProtoMessage() {}

func (x *IsSupportedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_proto_v1_drain_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsSupportedRequest.ProtoReflect.Descriptor instead.
func (*IsSupportedRequest) Descriptor() ([]byte, []int) {
	return file_api_plugins_proto_v1_drain_plugin_proto_rawDescGZIP(), []int{5}
}

type IsDrainOkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsDrainOkResponse) Reset() {
	*x = IsDrainOkResponse{}
	mi := &file_api_plugins_proto_v1_drain_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsDrainOkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsDrainOkResponse) ProtoMessage() {}

func (x *IsDrainOkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_proto_v1_drain_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsDrainOkResponse.ProtoReflect.Descriptor instead.
func (*IsDrainOkResponse) Descriptor() ([]byte, []int) {
	return file_api_plugins_proto_v1_drain_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *IsDrainOkResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type IsDrainOkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsDrainOkRequest) Reset() {
	*x = IsDrainOkRequest{}
	mi := &file_api_plugins_proto_v1_drain_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsDrainOkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsDrainOkRequest) ProtoMessage() {}

func (x *IsDrainOkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_proto_v1_drain_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsDrainOkRequest.ProtoReflect.Descriptor instead.
func (*IsDrainOkRequest) Descriptor() ([]byte, []int) {
	return file_api_plugins_proto_v1_drain_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *IsDrainOkRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type PreDrainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreDrainRequest) Reset() {
	*x = PreDrainRequest{}
	mi := &file_api_plugins_proto_v1_drain_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreDrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreDrainRequest) ProtoMessage() {}

func (x *PreDrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_proto_v1_drain_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreDrainRequest.ProtoReflect.Descriptor instead.
func (*PreDrainRequest) Descriptor() ([]byte, []int) {
	return file_api_plugins_proto_v1_drain_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *PreDrainRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type PreDrainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreDrainResponse) Reset() {
	*x = PreDrainResponse{}
	mi := &file_api_plugins_proto_v1_drain_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreDrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreDrainResponse) ProtoMessage() {}

func (x *PreDrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_proto_v1_drain_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreDrainResponse.ProtoReflect.Descriptor instead.
func (*PreDrainResponse) Descriptor() ([]byte, []int) {
	return file_api_plugins_proto_v1_drain_plugin_proto_rawDescGZIP(), []int{9}
}

type PostDrainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostDrainRequest) Reset() {
	*x = PostDrainRequest{}
	mi := &file_api_plugins_proto_v1_drain_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostDrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostDrainRequest) ProtoMessage() {}

func (x *PostDrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_proto_v1_drain_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostDrainRequest.ProtoReflect.Descriptor instead.
func (*PostDrainRequest) Descriptor() ([]byte, []int) {
	return file_api_plugins_proto_v1_drain_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *PostDrainRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type PostDrainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostDrainResponse) Reset() {
	*x = PostDrainResponse{}
	mi := &file_api_plugins_proto_v1_drain_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostDrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostDrainResponse) ProtoMessage() {}

func (x *PostDrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_proto_v1_drain_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostDrainResponse.ProtoReflect.Descriptor instead.
func (*PostDrainResponse) Descriptor() ([]byte, []int) {
	return file_api_plugins_proto_v1_drain_plugin_proto_rawDescGZIP(), []int{11}
}

var File_api_plugins_proto_v1_drain_plugin_proto protoreflect.FileDescriptor

const file_api_plugins_proto_v1_drain_plugin_proto_rawDesc = "" +
	"\n" +
	"'api/plugins/proto/v1/drain_plugin.proto\x12\x14api.plugins.proto.v1\"\r\n" +
	"\vInitRequest\"\x1e\n" +
	"\fInitResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x13IsSupportedResponse\x12\x1c\n" +
	"\tsupported\x18\x01 \x01(\bR\tsupported\"\x12\n" +
	"\x10IsHealthyRequest\"-\n" +
	"\x11IsHealthyResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\"\x14\n" +
	"\x12IsSupportedRequest\"#\n" +
	"\x11IsDrainOkResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"/\n" +
	"\x10IsDrainOkRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\".\n" +
	"\x0fPreDrainRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\"\x12\n" +
	"\x10PreDrainResponse\"/\n" +
	"\x10PostDrainRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\"\x13\n" +
	"\x11PostDrainResponse2\xb6\x04\n" +
	"\fDrainService\x12M\n" +
	"\x04Init\x12!.api.plugins.proto.v1.InitRequest\x1a\".api.plugins.proto.v1.InitResponse\x12b\n" +
	"\vIsSupported\x12(.api.plugins.proto.v1.IsSupportedRequest\x1a).api.plugins.proto.v1.IsSupportedResponse\x12\\\n" +
	"\tIsHealthy\x12&.api.plugins.proto.v1.IsHealthyRequest\x1a'.api.plugins.proto.v1.IsHealthyResponse\x12\\\n" +
	"\tIsDrainOk\x12&.api.plugins.proto.v1.IsDrainOkRequest\x1a'.api.plugins.proto.v1.IsDrainOkResponse\x12Y\n" +
	"\bPreDrain\x12%.api.plugins.proto.v1.PreDrainRequest\x1a&.api.plugins.proto.v1.PreDrainResponse\x12\\\n" +
	"\tPostDrain\x12&.api.plugins.proto.v1.PostDrainRequest\x1a'.api.plugins.proto.v1.PostDrainResponseB\xb5\x01\n" +
	"\x18com.api.plugins.proto.v1B\x10DrainPluginProtoP\x01Z\x14api/plugins/proto/v1\xa2\x02\x03APP\xaa\x02\x14Api.Plugins.Proto.V1\xca\x02\x14Api\\Plugins\\Proto\\V1\xe2\x02 Api\\Plugins\\Proto\\V1\\GPBMetadata\xea\x02\x17Api::Plugins::Proto::V1b\x06proto3"

var (
	file_api_plugins_proto_v1_drain_plugin_proto_rawDescOnce sync.Once
	file_api_plugins_proto_v1_drain_plugin_proto_rawDescData []byte
)

func file_api_plugins_proto_v1_drain_plugin_proto_rawDescGZIP() []byte {
	file_api_plugins_proto_v1_drain_plugin_proto_rawDescOnce.Do(func() {
		file_api_plugins_proto_v1_drain_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_plugins_proto_v1_drain_plugin_proto_rawDesc), len(file_api_plugins_proto_v1_drain_plugin_proto_rawDesc)))
	})
	return file_api_plugins_proto_v1_drain_plugin_proto_rawDescData
}

var file_api_plugins_proto_v1_drain_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_plugins_proto_v1_drain_plugin_proto_goTypes = []any{
	(*InitRequest)(nil),         // 0: api.plugins.proto.v1.InitRequest
	(*InitResponse)(nil),        // 1: api.plugins.proto.v1.InitResponse
	(*IsSupportedResponse)(nil), // 2: api.plugins.proto.v1.IsSupportedResponse
	(*IsHealthyRequest)(nil),    // 3: api.plugins.proto.v1.IsHealthyRequest
	(*IsHealthyResponse)(nil),   // 4: api.plugins.proto.v1.IsHealthyResponse
	(*IsSupportedRequest)(nil),  // 5: api.plugins.proto.v1.IsSupportedRequest
	(*IsDrainOkResponse)(nil),   // 6: api.plugins.proto.v1.IsDrainOkResponse
	(*IsDrainOkRequest)(nil),    // 7: api.plugins.proto.v1.IsDrainOkRequest
	(*PreDrainRequest)(nil),     // 8: api.plugins.proto.v1.PreDrainRequest
	(*PreDrainResponse)(nil),    // 9: api.plugins.proto.v1.PreDrainResponse
	(*PostDrainRequest)(nil),    // 10: api.plugins.proto.v1.PostDrainRequest
	(*PostDrainResponse)(nil),   // 11: api.plugins.proto.v1.PostDrainResponse
}
var file_api_plugins_proto_v1_drain_plugin_proto_depIdxs = []int32{
	0,  // 0: api.plugins.proto.v1.DrainService.Init:input_type -> api.plugins.proto.v1.InitRequest
	5,  // 1: api.plugins.proto.v1.DrainService.IsSupported:input_type -> api.plugins.proto.v1.IsSupportedRequest
	3,  // 2: api.plugins.proto.v1.DrainService.IsHealthy:input_type -> api.plugins.proto.v1.IsHealthyRequest
	7,  // 3: api.plugins.proto.v1.DrainService.IsDrainOk:input_type -> api.plugins.proto.v1.IsDrainOkRequest
	8,  // 4: api.plugins.proto.v1.DrainService.PreDrain:input_type -> api.plugins.proto.v1.PreDrainRequest
	10, // 5: api.plugins.proto.v1.DrainService.PostDrain:input_type -> api.plugins.proto.v1.PostDrainRequest
	1,  // 6: api.plugins.proto.v1.DrainService.Init:output_type -> api.plugins.proto.v1.InitResponse
	2,  // 7: api.plugins.proto.v1.DrainService.IsSupported:output_type -> api.plugins.proto.v1.IsSupportedResponse
	4,  // 8: api.plugins.proto.v1.DrainService.IsHealthy:output_type -> api.plugins.proto.v1.IsHealthyResponse
	6,  // 9: api.plugins.proto.v1.DrainService.IsDrainOk:output_type -> api.plugins.proto.v1.IsDrainOkResponse
	9,  // 10: api.plugins.proto.v1.DrainService.PreDrain:output_type -> api.plugins.proto.v1.PreDrainResponse
	11, // 11: api.plugins.proto.v1.DrainService.PostDrain:output_type -> api.plugins.proto.v1.PostDrainResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_plugins_proto_v1_drain_plugin_proto_init() }
func file_api_plugins_proto_v1_drain_plugin_proto_init() {
	if File_api_plugins_proto_v1_drain_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_plugins_proto_v1_drain_plugin_proto_rawDesc), len(file_api_plugins_proto_v1_drain_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_plugins_proto_v1_drain_plugin_proto_goTypes,
		DependencyIndexes: file_api_plugins_proto_v1_drain_plugin_proto_depIdxs,
		MessageInfos:      file_api_plugins_proto_v1_drain_plugin_proto_msgTypes,
	}.Build()
	File_api_plugins_proto_v1_drain_plugin_proto = out.File
	file_api_plugins_proto_v1_drain_plugin_proto_goTypes = nil
	file_api_plugins_proto_v1_drain_plugin_proto_depIdxs = nil
}
