name: Helm package
on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'


jobs:
  helm-package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./.github/workflows/env_setup

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Verify Helm installation
        run: helm version

      - name: Login to GitHub Container Registry
        if: env.PROTECTED_RUN == 'true'
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Helm package
        run: |
          export VERSION=999
          if [[ "${{ github.ref_type }}" == "tag" && "${{ github.ref_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            export VERSION=$(echo -n "${{ github.ref_name }}" | sed 's/^v//g')
          fi
          helm package dist/chart -u --version ${VERSION} --app-version ${VERSION}
          if [[ "${VERSION}" != "999" && "${PROTECTED_RUN}" == "true" ]]; then
            helm push "nodedrain-${VERSION}.tgz" "oci://ghcr.io/slyngdk/charts"
          fi
